# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: CC0-1.0

[harvest]
from = [ "cff", "git" ]

[harvest.cff]
validate = false

[deposit]
mapping = "invenio"
target = "invenio"

[deposit.invenio]
site_url = "https://sandbox.zenodo.org"
api_paths = { depositions = "api/deposit/depositions", licenses = "api/licenses", communities = "api/communities" }
schema_paths = { record = "api/schemas/records/record-v1.0.0.json" }
record_id = 1177603
communities = ["zenodo"]
