# SPDX-FileCopyrightText: 2022 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: CC0-1.0

# SPDX-FileContributor: Stephan Druskat
# SPDX-FileContributor: Michael Meinel
# SPDX-FileContributor: David Pape

[tool.poetry]
name = "hermes"
version = "0.1.0"
description = "Workflow to publish research software with rich metadata"
homepage = "https://software-metadata.pub"
license = "Apache-2.0"
authors = [
    "Stephan Druskat <stephan.druskat@dlr.de>",
    "Michael Meinel <michael.meinel@dlr.de>",
    "Oliver Bertuch <o.bertuch@fz-juelich.de>",
    "Jeffrey Kelling <j.kelling@hzdr.de>",
    "Oliver Knodel <o.knodel@hzd.r.de>"
]

readme = "README.md"
repository = "https://github.com/hermes-hmc/workflow"
documentation = "https://docs.software-metadata.pub"
keywords = ["publishing", "metadata", "automation"]

include = [
    "hermes/schema/*.json",
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1"
"ruamel.yaml" = "^0.17.21"
jsonschema = "^3.0.0"
cffconvert = "^2.0.0"
convert-codemeta = "^0.4.0"
toml = "^0.10.2"
pyparsing = "^3.0.9"
requests = "^2.28.1"

# Packages for developers
[tool.poetry.group.dev.dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
taskipy = "^1.10.3"
flake8 = "^5.0.4"

# Packages for developers for creating documentation
[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
Sphinx = "^4.5.0"
# Sphinx - Additional modules
myst-parser = "^0.18.0"
sphinx-book-theme = "^0.3.3"
sphinx-favicon = "^0.2"
sphinxcontrib-contentui = "^0.2.5"
sphinxcontrib-images = "^0.9.4"
sphinx-icon = "^0.1.2"
sphinx-autobuild = "^2021.3.14"
sphinx-autoapi = "^2.0.0"
sphinxemoji = "^0.2.0"
sphinxext-opengraph = "^0.6.3"
reuse = "^1.0.0"

[tool.poetry.plugins.console_scripts]
hermes = "hermes.cli:main"

[tool.poetry.plugins."hermes.harvest"]
000_cff = "hermes.commands.harvest.cff:harvest_cff"
010_codemeta = "hermes.commands.harvest.codemeta:harvest_codemeta"
020_git = "hermes.commands.harvest.git:harvest_git"

[tool.poetry.plugins."hermes.preprocess"]
000_cff = "hermes.commands.process.cff:add_name"
020_git = "hermes.commands.process.git:process"

[tool.poetry.plugins."hermes.prepare_deposit"]
invenio = "hermes.commands.deposit.invenio:prepare_deposit"

[tool.taskipy.tasks]
docs-build = "poetry run sphinx-build -M html docs/source docs/build -W"
docs-clean = "poetry run sphinx-build -M clean docs/source docs/build"
docs-live = "poetry run sphinx-autobuild docs/source docs/build"
flake8 = "poetry run flake8 ./test/ ./src/ --count --select=E9,F63,F7,F82 --statistics"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
