[tool.poetry]
name = "hermes"
version = "0.1.0"
description = "Workflow to publish research software with rich metadata"
authors = ["Stephan Druskat <stephan.druskat@dlr.de>", "Michael Meinel <michael.meinel@dlr.de"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"

[tool.poetry.plugins.console_scripts]
haggis = "hermes.cli:haggis"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
